name: Secure DevOps Pipeline

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install semgrep pip-audit

      # ---------------- SAST ---------------- #
      - name: Run Semgrep
        run: |
          mkdir -p reports
          semgrep --config=p/owasp-top-ten \
                  --config=p/python \
                  --json \
                  app/ > reports/semgrep.json

      # ---------------- SECRET SCAN ---------------- #
      - name: Run TruffleHog
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/app:/repo \
          ghcr.io/trufflesecurity/trufflehog:latest \
          filesystem /repo --json > reports/secrets.json

      # ---------------- DEPENDENCY ---------------- #
      - name: Install Dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run Dependency Scan
        run: |
          pip-audit -r app/requirements.txt -f json > reports/dependency.json

      # ---------------- PUSH REPORTS ---------------- #
      - name: Push Reports to Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git pull origin main --rebase

          git add reports/

          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update reports"

          git push