name: Secret Scan (TruffleHog)

on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: .
      continue-on-error: true