name: Secret Scan

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: trufflesecurity/trufflehog@main
      with:
        path: app/