name: Secret Scan

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run TruffleHog Scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo ghcr.io/trufflesecurity/trufflehog:latest \
        filesystem /repo