name: SAST Scan

on:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep and FAIL if issues found
      run: |
        semgrep --config=auto app/ --error